nodeLinker: node-modules

packageExtensions:
  "@vuetify/loader-shared@*":
    peerDependenciesMeta:
      vue:
        optional: true
  vue-demi@*:
    peerDependenciesMeta:
      vue:
        optional: true

yarnPath: .yarn/releases/yarn-4.0.0.cjs
