nodeLinker: node-modules

packageExtensions:
  "@vuetify/loader-shared@*":
    peerDependenciesMeta:
      vue:
        optional: true
  vue-cli-plugin-vuetify@*:
    peerDependenciesMeta:
      webpack:
        optional: true

yarnPath: .yarn/releases/yarn-3.4.1.cjs
