nodeLinker: node-modules

packageExtensions:
  "@vuetify/loader-shared@*":
    peerDependenciesMeta:
      vue:
        optional: true
  laravel-vite-plugin@*:
    dependencies:
      picocolors: ^1.0.0
  vue-cli-plugin-vuetify@*:
    peerDependenciesMeta:
      webpack:
        optional: true

yarnPath: .yarn/releases/yarn-3.3.0.cjs
