nodeLinker: node-modules

packageExtensions:
  laravel-vite-plugin@*:
    dependencies:
      picocolors: ^1.0.0
  vue-cli-plugin-vuetify@*:
    peerDependenciesMeta:
      webpack:
        optional: true
  "@vuetify/loader-shared@*":
     peerDependenciesMeta:
       vue:
         optional: true

yarnPath: .yarn/releases/yarn-3.2.4.cjs
